#!/usr/bin/env node
/**
 * Turso Database Setup Script
 * ============================
 * Skrip ini membuat database Turso dan menjalankan migration SQL.
 * 
 * Prasyarat:
 *   1. Install Turso CLI: https://docs.turso.tech/cli/installation
 *      Windows (via scoop): scoop install turso-cli
 *      Atau via npm: npm install -g @turso/cli
 *   2. Login: turso auth login
 *   3. Jalankan: node scripts/setup-turso.mjs
 */

import { execSync } from 'child_process';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');

const DB_NAME = 'rfx-wedding-saas';

function run(cmd, opts = {}) {
  console.log(`\n> ${cmd}`);
  try {
    const output = execSync(cmd, { encoding: 'utf-8', stdio: 'pipe', ...opts });
    if (output.trim()) console.log(output.trim());
    return output.trim();
  } catch (err) {
    console.error(`Error: ${err.stderr || err.message}`);
    return null;
  }
}

async function main() {
  console.log('='.repeat(50));
  console.log('  Wedding SaaS — Turso Database Setup');
  console.log('='.repeat(50));

  // Step 1: Check Turso CLI
  console.log('\n[1/5] Checking Turso CLI...');
  const tursoVersion = run('turso --version');
  if (!tursoVersion) {
    console.error('\n❌ Turso CLI tidak ditemukan!');
    console.log('   Install via: npm install -g @turso/cli');
    console.log('   Atau via scoop: scoop install turso-cli');
    console.log('   Docs: https://docs.turso.tech/cli/installation');
    process.exit(1);
  }
  console.log(`✅ Turso CLI: ${tursoVersion}`);

  // Step 2: Check auth
  console.log('\n[2/5] Checking Turso authentication...');
  const whoami = run('turso auth whoami');
  if (!whoami) {
    console.log('⚠️  Belum login. Menjalankan turso auth login...');
    run('turso auth login');
  } else {
    console.log(`✅ Logged in as: ${whoami}`);
  }

  // Step 3: Create database
  console.log(`\n[3/5] Creating database "${DB_NAME}"...`);
  const existingDbs = run('turso db list');
  if (existingDbs && existingDbs.includes(DB_NAME)) {
    console.log(`✅ Database "${DB_NAME}" sudah ada. Skip create.`);
  } else {
    const createResult = run(`turso db create ${DB_NAME} --location sin`);
    if (createResult === null) {
      console.error('❌ Gagal membuat database. Coba jalankan manual: turso db create ' + DB_NAME);
      process.exit(1);
    }
    console.log(`✅ Database "${DB_NAME}" berhasil dibuat!`);
  }

  // Step 4: Get connection info
  console.log('\n[4/5] Getting connection info...');
  const dbUrl = run(`turso db show ${DB_NAME} --url`);
  const dbToken = run(`turso db tokens create ${DB_NAME}`);

  if (!dbUrl || !dbToken) {
    console.error('❌ Gagal mendapatkan URL/Token. Coba jalankan manual:');
    console.log(`   turso db show ${DB_NAME} --url`);
    console.log(`   turso db tokens create ${DB_NAME}`);
    process.exit(1);
  }

  console.log(`✅ Database URL: ${dbUrl}`);
  console.log(`✅ Auth Token: ${dbToken.substring(0, 20)}...`);

  // Step 5: Run migration
  console.log('\n[5/5] Running migration...');
  const migrationPath = resolve(ROOT, 'migrations', '001_initial_schema.sql');
  
  if (!existsSync(migrationPath)) {
    console.error(`❌ Migration file not found: ${migrationPath}`);
    process.exit(1);
  }

  const migrationSql = readFileSync(migrationPath, 'utf-8');
  
  // Split by semicolon and run each statement
  const statements = migrationSql
    .split(';')
    .map(s => s.trim())
    .filter(s => s.length > 0 && !s.startsWith('--'));

  let successCount = 0;
  let errorCount = 0;
  
  for (const stmt of statements) {
    // Escape quotes for shell
    const escaped = stmt.replace(/'/g, "''").replace(/"/g, '\\"');
    const result = run(`turso db shell ${DB_NAME} "${stmt};"`);
    if (result !== null) {
      successCount++;
    } else {
      errorCount++;
      console.log(`⚠️  Statement failed (may already exist): ${stmt.substring(0, 60)}...`);
    }
  }

  console.log(`\n✅ Migration selesai: ${successCount} berhasil, ${errorCount} gagal/skip`);

  // Write .env.local
  console.log('\n📝 Writing .env.local...');
  const envContent = `# Turso Database (Auto-generated by setup script)
VITE_TURSO_DATABASE_URL=${dbUrl}
VITE_TURSO_AUTH_TOKEN=${dbToken}

# Cloudinary (preset terpisah untuk wedding)
VITE_CLOUDINARY_CLOUD_NAME=dxklmdbjv
VITE_CLOUDINARY_UPLOAD_PRESET=rfx_wedding

# Gemini API (opsional, utama tetap Puter.js)
GEMINI_API_KEY=

# App URL
VITE_APP_URL=https://undangankita.rfx.web.id
`;

  const envLocalPath = resolve(ROOT, '.env.local');
  writeFileSync(envLocalPath, envContent, 'utf-8');
  console.log(`✅ .env.local berhasil ditulis ke: ${envLocalPath}`);

  // Summary
  console.log('\n' + '='.repeat(50));
  console.log('  ✅ SETUP SELESAI!');
  console.log('='.repeat(50));
  console.log(`
Langkah selanjutnya:
  1. Pastikan .env.local sudah benar
  2. Buat preset "rfx_wedding" di Cloudinary Dashboard:
     https://console.cloudinary.com/settings/upload
  3. Jalankan: npm install @libsql/client
  4. Jalankan: npm run dev
  `);
}

main().catch(console.error);
